services:
  - type: web
    name: arginex-business
    runtime: python
    startCommand: python app.py
    envVars:
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
      - key: PORT
        value: "10000"
